version: '3.7'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2-php8.0-apache
    container_name: shinyu_wordpress
    restart: always
    volumes:
      - .:/var/www/html/wp-content/themes/shinyu
      - ./wp-app:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      WORDPRESS_DB_NAME: shinyu
      WORDPRESS_TABLE_PREFIX: 33FMzr6J2_
    ports:
      - 9050:80
    networks:
      - shinyu
  db:
    image: mariadb:latest
    container_name: shinyu_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - shinyu
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: shinyu_phpmyadmin
    restart: always
    ports:
      - 8050:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      UPLOAD_LIMIT: 300M
    networks:
      - shinyu
networks:
  shinyu:
volumes:
  db_data: